# 
# docker-compose.yml — определяет сервисы для разработки и тестирования.
#
#Что нужно сделать:
#  - Настроить сервисы для:
#      - PostgreSQL (или MySQL) с начальной базой.
#      - Приложения Spring Boot (если нужно).
#  - Открыть нужные порты (например, 5432, 8080).
#  - Настроить volume для хранения данных БД.

version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: postgres-bank
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bankdb
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql

